#!/usr/bin/env bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

(
    cd apps/cacvote-mark/backend
    rm -rf dev-workspace
)
(
    cd apps/cacvote-jx-terminal/backend
    cargo sqlx migrate run --source=db/migrations
)
(
    cd apps/cacvote-server/backend
    cargo sqlx migrate run --source=db/migrations
)