#!/usr/bin/env bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

(
    cd apps/cacvote-mark/backend
    rm -rf dev-workspace
)
(
    cd apps/cacvote-scan/backend
    cargo sqlx database reset -y --source=db/migrations
)
(
    cd apps/cacvote-jx-terminal/backend
    cargo sqlx database reset -y --source=db/migrations
)
(
    cd services/cacvote-server
    cargo sqlx database reset -y --source=db/migrations
)